import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { AppbarClient } from "../component/AppbarClient";
import { Bricolage_Grotesque } from "next/font/google";
import { Space_Mono } from "next/font/google";
import { cn } from "../lib/utils";

export const metadata: Metadata = {
  title: "Money Mingle",
  description: "Generated by create turbo",
};
const fontHeading = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = Space_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body
          className={cn("antialiased", fontHeading.variable, fontBody.variable)}
        >
          <AppbarClient />
          {children}
        </body>
      </Providers>
    </html>
  );
}
