import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { AppbarClient } from "../components/AppbarClient";

export const metadata: Metadata = {
  title: "Money Mingle",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body>
          <AppbarClient />
          {children}
        </body>
      </Providers>
    </html>
  );
}
